AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for VPC, IGW, Public Subnet, EC2 Instance, Security Group, and S3 Bucket for Group1(Mojtaba, Erdal, and Mikhail).

Resources:
  MyVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.0.0.0/16"

  MyInternetGateway:
    Type: "AWS::EC2::InternetGateway"

  AttachGateway:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway

  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: "10.0.0.0/24"
      AvailabilityZone: 'eu-central-1a'
      MapPublicIpOnLaunch: true

  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-04376654933b081a7"
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !GetAtt MySecurityGroup.GroupId

  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow incoming traffic on port 8000, SSH, HTTP, and HTTPS"
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 8000
          ToPort: 8000
          IpProtocol: "tcp"

  MyS3Bucket:
    Type: "AWS::S3::Bucket"

Outputs:
  VPCId:
    Description: "VPC ID"
    Value: !Ref MyVPC

  EC2InstanceId:
    Description: "EC2 Instance ID"
    Value: !Ref MyEC2Instance
